import type { Metadata } from "next";
//1 import { Geist, Geist_Mono } from "next/font/google"; //default comment
//2
import { DM_Sans } from "next/font/google";
import "./globals.css";

//3 only the latin subset
const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 4 add the font to the body */}
      <body className={`${dmSans.className} antialiased`}>{children}</body>
    </html>
  );
}
